name: beyond
description: beyond
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.12
  flutter_markdown_plus_latex: ^1.0.5
  google_fonts: ^6.3.3
  infinite_lazy_grid:
    git: https://github.com/ruinivist/infinite_lazy_grid.git
  re_editor: ^0.10.0
  re_highlight: ^0.0.3
  scribble: ^0.10.0+1
  scroll_animator: 0.3.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  uuid: ^4.6.0

dev_dependencies:
  flutter_math_fork: ^0.7.4
  flutter_test:
    sdk: flutter
  # Used by web tests to register the browser storage implementation.
  shared_preferences_web: ^2.4.3
  url_launcher_platform_interface: ^2.3.2
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
